#minimum and maximum fimder🙄🙄🙄
import time
print(".")
time.sleep(1)
print(".")
time.sleep(1)
print("what is your name")
a = input()
print("fine " + a  + " welcome to ")
time.sleep(1)
print("Welcome TO Code-with-abid hacking world!!")
time.sleep(1)
print("\n")
print("ok now answer these questions")
time.sleep(1)
print("have you ever hacked before?,\n1= yes\n 2=no")
b = input()
if "1" in b:
  print("ok that means you are a hacker.try this")
if "0" in b:
  print("ok you can use this")
time.sleep(1)
print("ok now enter the client's name")
c = input()
print("enter IP ADRESS of " + c)
d = input()
if len(d) < 5:
  print("invalid IP ADRESS. run this code again")
else:
   print("checking database of " + c)
   time.sleep(1)
   print("10% of 100")
   time.sleep(2)
   print("50% of 100")
   time.sleep(2)
   print("90% of 100")
   time.sleep(2)
   print("98% of 100")
   time.sleep(4)
   print("100% loaded")
   time.sleep(1)
   print("leaking info")
   time.sleep(1)
   print("found 46 files in " + c +" database")
   time.sleep(1)
   print("15 roots found")
   time.sleep(1)
   print("19 files found in data.main")
   time.sleep(1)
   print("copying leaked info to my db")
   time.sleep(3)
   print("process finished")
   time.sleep(1)
   print("uploading file in " +c + " network")
   time.sleep(3)
   print("process finished")
   time.sleep(1)
   print(c + " data has been copied successfully")
   time.sleep(1)
   print("hope you liked my work " +a)
   time.sleep(1)
   print("\n")
   print("give me a star if you liked me☺️")